# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'chat_app.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.text_browser = QtWidgets.QTextBrowser(self.centralwidget)
        self.text_browser.setGeometry(QtCore.QRect(190, 10, 581, 431))
        self.text_browser.setObjectName("text_browser")
        self.line_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.line_edit.setGeometry(QtCore.QRect(190, 450, 481, 41))
        self.line_edit.setObjectName("line_edit")
        self.send_button = QtWidgets.QPushButton(self.centralwidget)
        self.send_button.setGeometry(QtCore.QRect(670, 450, 101, 41))
        self.send_button.setObjectName("send_button")
        self.radio_user_a = QtWidgets.QRadioButton(self.centralwidget)
        self.radio_user_a.setEnabled(True)
        self.radio_user_a.setGeometry(QtCore.QRect(90, 10, 61, 31))
        self.radio_user_a.setAutoExclusive(False)
        self.radio_user_a.setObjectName("radio_user_a")
        self.radio_user_b = QtWidgets.QRadioButton(self.centralwidget)
        self.radio_user_b.setGeometry(QtCore.QRect(90, 49, 61, 31))
        self.radio_user_b.setAutoExclusive(False)
        self.radio_user_b.setObjectName("radio_user_b")
        self.radio_user_c = QtWidgets.QRadioButton(self.centralwidget)
        self.radio_user_c.setGeometry(QtCore.QRect(90, 90, 61, 31))
        self.radio_user_c.setAutoExclusive(False)
        self.radio_user_c.setObjectName("radio_user_c")
        self.radio_group = QtWidgets.QRadioButton(self.centralwidget)
        self.radio_group.setGeometry(QtCore.QRect(90, 120, 91, 41))
        self.radio_group.setObjectName("radio_group")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.send_button.setText(_translate("MainWindow", "send"))
        self.radio_user_a.setText(_translate("MainWindow", "A"))
        self.radio_user_b.setText(_translate("MainWindow", "B"))
        self.radio_user_c.setText(_translate("MainWindow", "C"))
        self.radio_group.setText(_translate("MainWindow", "Send To All"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
