# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'new_group.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(224, 302)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setObjectName("widget")
        self.user_a = QtWidgets.QRadioButton(self.widget)
        self.user_a.setGeometry(QtCore.QRect(60, 20, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.user_a.setFont(font)
        self.user_a.setAutoExclusive(False)
        self.user_a.setObjectName("user_a")
        self.user_b = QtWidgets.QRadioButton(self.widget)
        self.user_b.setGeometry(QtCore.QRect(60, 70, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.user_b.setFont(font)
        self.user_b.setAutoExclusive(False)
        self.user_b.setObjectName("user_b")
        self.user_c = QtWidgets.QRadioButton(self.widget)
        self.user_c.setGeometry(QtCore.QRect(60, 120, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.user_c.setFont(font)
        self.user_c.setAutoExclusive(False)
        self.user_c.setObjectName("user_c")
        self.create_btn = QtWidgets.QPushButton(self.widget)
        self.create_btn.setGeometry(QtCore.QRect(-70, 190, 331, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.create_btn.setFont(font)
        self.create_btn.setObjectName("create_btn")
        self.gridLayout.addWidget(self.widget, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.user_a.setText(_translate("Dialog", "User A"))
        self.user_b.setText(_translate("Dialog", "User B"))
        self.user_c.setText(_translate("Dialog", "User C"))
        self.create_btn.setText(_translate("Dialog", "Create"))
